# bundle exec jekyll serve --host=0.0.0.0

title: MycilaHADiscovery
description: Simple and efficient ome Assistant Discovery library for Arduino / ESP32
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
